server:
  port: 19999 # 运行端口
spring:
  application:
    name: no-work # 项目名
  profiles:
    active: dev # 指定当前运行环境
  datasource: # 数据源
    url: jdbc:mysql://${no-work.mysql.ip:127.0.0.1}:${no-work.mysql.port:3306}/${no-work.mysql.db:no-work}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${no-work.mysql.username:root}
    password: ${no-work.mysql.password:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${no-work.redis.host:127.0.0.1}
      port: ${no-work.redis.port:6379}
      database: 0 # 指定默认数据库
      timeout: 1800000
      password: ${no-work.redis.password:}
springdoc: # springdoc-openapi项目配置
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: con.ershi
knife4j: # knife4j的增强配置，不需要增强可以不配
  enable: true
  setting:
    language: zh_cn
